# Generated by Django 5.0.4 on 2024-04-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
