# Generated by Django 5.0.4 on 2024-05-06 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibrary', '0002_usuario_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='album',
            name='anio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
